set FREQDIFF=1.0

set HAUPTFOLDER=ModulesBestSites\
set LIB=ModulesBestSitesAll.dat

set MINCOVERY=90
set MAXCOVERN=50
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%

set MINCOVERY=75
set MAXCOVERN=50
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%

set MINCOVERY=66
set MAXCOVERN=50
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%

set MINCOVERY=50
set MAXCOVERN=25
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%

set MINCOVERY=33
set MAXCOVERN=15
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%


rem **************************************************************************************
set HAUPTFOLDER=Modules_w100\
set LIB=ModulesBasedOnCE.dat

set MINCOVERY=90
set MAXCOVERN=50
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%

set MINCOVERY=75
set MAXCOVERN=50
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%

set MINCOVERY=66
set MAXCOVERN=50
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%

set MINCOVERY=50
set MAXCOVERN=25
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%

set MINCOVERY=33
set MAXCOVERN=15
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%

rem **************************************************************************************
set HAUPTFOLDER=Modules_w50\
set LIB=ModulesBasedOnCE.dat

set MINCOVERY=90
set MAXCOVERN=50
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod_w50.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%

set MINCOVERY=75
set MAXCOVERN=50
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod_w50.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%

set MINCOVERY=66
set MAXCOVERN=50
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod_w50.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%

set MINCOVERY=50
set MAXCOVERN=25
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod_w50.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%

set MINCOVERY=33
set MAXCOVERN=15
set FOLDER=%HAUPTFOLDER%MODOUT0%MINCOVERY%_0%MAXCOVERN%
mkdir %FOLDER%
call go_mod_w50.bat %LIB% 0.%MINCOVERY% 0.%MAXCOVERN% %FOLDER% %MINCOVERY%
