start /LOW /B /WAIT mmmodules.exe  %1  Breast500.out.bin       BreastNot500.out.bin     MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Breast500_0%5.CEout    
start /LOW /B /WAIT mmmodules.exe  %1  Cerebellum500.out.bin   CerebellumNot500.out.bin MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Cerebellum500_0%5.CEout
start /LOW /B /WAIT mmmodules.exe  %1  Heart500.out.bin        HeartNot500.out.bin      MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Heart500_0%5.CEout     
start /LOW /B /WAIT mmmodules.exe  %1  Kidney500.out.bin       KidneyNot500.out.bin     MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Kidney500_0%5.CEout    
start /LOW /B /WAIT mmmodules.exe  %1  Liver500.out.bin        LiverNot500.out.bin      MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Liver500_0%5.CEout     
start /LOW /B /WAIT mmmodules.exe  %1  Muscle500.out.bin       MuscleNot500.out.bin     MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Muscle500_0%5.CEout    
start /LOW /B /WAIT mmmodules.exe  %1  Pancreas500.out.bin     PancreasNot500.out.bin   MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Pancreas500_0%5.CEout  
start /LOW /B /WAIT mmmodules.exe  %1  Prostate500.out.bin     ProstateNot500.out.bin   MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Prostate500_0%5.CEout  
start /LOW /B /WAIT mmmodules.exe  %1  Spleen500.out.bin       SpleenNot500.out.bin     MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Spleen500_0%5.CEout    
start /LOW /B /WAIT mmmodules.exe  %1  Testes500.out.bin       TestesNot500.out.bin     MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Testes500_0%5.CEout    
start /LOW /B /WAIT mmmodules.exe  %1  Thyroid500.out.bin      ThyroidNot500.out.bin    MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Thyroid500_0%5.CEout   
start /LOW /B /WAIT mmmodules.exe  %1  Breast1k.out.bin       BreastNot1k.out.bin     MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Breast1k_0%5.CEout    
start /LOW /B /WAIT mmmodules.exe  %1  Cerebellum1k.out.bin   CerebellumNot1k.out.bin MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Cerebellum1k_0%5.CEout
start /LOW /B /WAIT mmmodules.exe  %1  Heart1k.out.bin        HeartNot1k.out.bin      MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Heart1k_0%5.CEout     
start /LOW /B /WAIT mmmodules.exe  %1  Kidney1k.out.bin       KidneyNot1k.out.bin     MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Kidney1k_0%5.CEout    
start /LOW /B /WAIT mmmodules.exe  %1  Liver1k.out.bin        LiverNot1k.out.bin      MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Liver1k_0%5.CEout     
start /LOW /B /WAIT mmmodules.exe  %1  Muscle1k.out.bin       MuscleNot1k.out.bin     MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Muscle1k_0%5.CEout    
start /LOW /B /WAIT mmmodules.exe  %1  Pancreas1k.out.bin     PancreasNot1k.out.bin   MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Pancreas1k_0%5.CEout  
start /LOW /B /WAIT mmmodules.exe  %1  Prostate1k.out.bin     ProstateNot1k.out.bin   MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Prostate1k_0%5.CEout  
start /LOW /B /WAIT mmmodules.exe  %1  Spleen1k.out.bin       SpleenNot1k.out.bin     MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Spleen1k_0%5.CEout    
start /LOW /B /WAIT mmmodules.exe  %1  Testes1k.out.bin       TestesNot1k.out.bin     MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Testes1k_0%5.CEout    
start /LOW /B /WAIT mmmodules.exe  %1  Thyroid1k.out.bin      ThyroidNot1k.out.bin    MinCoverY %2 MaxCoverN %3 FreqDiff 1 >  %4\Thyroid1k_0%5.CEout   
